# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- platformio run
before_deploy:
  - cp .pioenvs/esp8285/firmware.bin ./sonoff_plug.bin
  - cp .pioenvs/d1_mini/firmware.bin ./d1_mini.bin
  - echo "copyied files"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: sIswHS7uMro+IEW+N+GAAa+vB546/RCto2s1UAsCMcmfbSuWWDReVoH1LnbAV2wSVPF0NjcMIyhm5YzDCI1pRdooFTDkE9X5paLM60eduTGY41jKfFCWBWl/cHPjyZYiFpDKd2OmJnK8WNsMp0Qr2K1DAzlmPwPs6u7E3vePJGtgJjadbuvw/vchOCcO/VI4tV8SOIeQLiUhpxeV3Qu1f0V9v/E4BnDYseX7LR4oXHSHzATmhVcILXkET7thfCowuC8yHZVuryleW4YM6pwczj1bJZKZn19pJoFh3rF3Q8J6xIFMULSJ3f4ege6WvAvvi0+5yoyAVvrQEkr2e+im4IBtNVIoMgQwZ94i9d7XS3xcZxbp8Fn7/xl/74E+UsJ0FlUymWqojt0bCemJhk7cjr0p8gJA29cCQXqFg1Hfgszt/T23QtVysilZGZpKogGmZYb/Q3n//WxgdRLgcSGySv9a43Vv5wwPnlYzulxJYg8QUwnYnrltFpG+8qhaOo2EQAdjC28+Ud5Nopt4c6jJluSE5aPm+pjo+LHAJgZvb+BME+D6JEb5MzdZa06M97c+VLiYTpBdDuhkPUFcLNTR22/E1HUJNK4Ju1PK03IUU/5uGXM7uJb1ZiALienEq04X3djxkOhQRFW1FSjW/gpNyre1OL9C+plpM8mRDEWpiug=
  file:
    - "./sonoff_plug.bin"
    - "./d1_mini.bin"
  on:
    repo: georgeF105/ioatt-device
    tags: true
